package am.ak.spring.data;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import static org.junit.Assert.assertNotNull;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'karlen' at '3/10/17 10:59 PM' with Gradle 2.10
 *
 * @author karlen, @date 3/10/17 10:59 PM
 */
public class BaseTest {

    protected static ApplicationContext applicationContext;

    @BeforeClass
    public static void setUp() {
        applicationContext = new ClassPathXmlApplicationContext("application.xml");
    }
}
