//import org.junit.Test;
//import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'karlen' at '3/10/17 10:59 PM' with Gradle 2.10
 *
 * @author karlen, @date 3/10/17 10:59 PM
 */
public class LibraryTest {
    //@Test public void testSomeLibraryMethod() {
      //  Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    //}
}
